#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

replacement="server_name _;\n\trewrite ^\/redirect_me$ https:\/\/github.com permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default
sudo service nginx start

