#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/callmhejerry permanent;/" /etc/nginx/sites-available/default
sudo service nginx start

