#!/usr/bin/env bash
# configure nginx server to have a custom 404 page
sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement="server_name _;\n\trewrite ^\/redirect_me to https://github.com/callmhejerry permanent"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/custom_error.html
sudo sed -i '/server_name _;/a \\terror_page 404 \/custom_error.html;' /etc/nginx/sites-available/default
sudo service nginx start
