#!/usr/bin/env bash
# configure nginx server to have a custom 404 page
sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement="server_name _;\n\trewrite ^\/redirect_me to https:\/\/github.com/callmhejerry permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_error.html
error_string="listen 80 default_server;\n\terror_page 404 \/custom_error.html;\n\tlocation = \/custom_error.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$error_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
