#!/usr/bin/env bash
# configure nginx server to have a custom 404 page
sudo apt update -y
sudo apt install nginx -y
echo "Ceci n'est pas une page" > /var/www/html/custom_error.html
sed -i '/server_name _;/a \\terror_page 404 \/custom_error.html;' /etc/nginx/sites-available/default
sudo service nginx start
