#!/usr/bin/env bash

#install haproxy
sudo apt update
sudo apt install haproxy -y

# configure haproxy

config=\
"
frontend jeremiah-frontend
	bind *:80
	mode http
	default_backend jeremiah-backend

backend jeremiah-backend
	balance roundrobin
	server 150961-web-01 54.90.61.225:80 check
	server 150961-web-02 52.87.25.122:80 check
"

echo $config | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
