#!/usr/bin/env bash
# A script that displays listening ports:
# That only shows listening sockets
# That only shows the PID and name of the program to which each socket belongs
netstat --listening --program
