#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd
# It displays only 
# username
# user id
# Home directory path for user

file="/etc/passwd"

while read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < $file
